🚀 도메인 분석
next-step/career-domain pull request #24
Opened 2023-12-03 13:04 UTC by joel-you

저희 시스템에서 모델링이 그나마 적합하다고 생각한 랭크와 보상 시스템에 대한 모델링을 해보았습니다.

2023-12-04 11:06 UTC, titlet reviewed
게임쪽 랭크에 따른 보상 시스템 으로 보여지네요. 
상위 level에서 추상화는 잘 이해가 되는데 domain들간의 관계는 살짝 아쉬운 부분이 있어 보입니다. 

1. Hand data가 게임내에서 랭크를 결정하는 데이터라고 보여지는데 맞을까요? 맞다면 Point history, Rank History가 점선사각형 안에 같이 있는 부분이 어떤 의미인지 궁금하네요. - 별도로 분리하는게 맞지 않을까? 생각 됩니다. 
2. Reward의 컨벤션이 이상한건지 그림상으로 보면 Attendee가 생성될때 이미 Reward는 있는것으로 보여지네요. (어텐디가 후보자라면 rank가 정해질때 reward랑 연결 되어야 하는게 아닐지? 그게 혹시 prize인건지?)
3. credit, debit, cancel이 하나로 표현했는데 각각의 flow가 약간씩 다를 것 같네요 - 이부분은 당장 수정을 할 필요는 없구요 기본 도메인을 그리면 화살표만 몇개 바꾸거나 하면 될것 으로 예상되어 추후 각각의 문서로 만들어 보는것도 좋을것 같네요. 

아마 제가 도메인을 자세히 몰라서 이해를 못한것일 수 있습니다. '보상결정', '순위결정' 같은 설명이 어딘가 추가된다면 좀더 이해가 편하지 않을까? 하네요.

2023-12-04 11:07 UTC, titlet requested changes
추상화를 잘해서 그려주신 것 같습니다. 
comment로 몇가지 문의를 남겼는데 확인 후 리뷰요청 부탁드립니다.

2023-12-05 10:48 UTC, joel-you commented
> 게임쪽 랭크에 따른 보상 시스템 으로 보여지네요. 상위 level에서 추상화는 잘 이해가 되는데 domain들간의 관계는 살짝 아쉬운 부분이 있어 보입니다.
> 
> 1. Hand data가 게임내에서 랭크를 결정하는 데이터라고 보여지는데 맞을까요? 맞다면 Point history, Rank History가 점선사각형 안에 같이 있는 부분이 어떤 의미인지 궁금하네요. - 별도로 분리하는게 맞지 않을까? 생각 됩니다.
> 2. Reward의 컨벤션이 이상한건지 그림상으로 보면 Attendee가 생성될때 이미 Reward는 있는것으로 보여지네요. (어텐디가 후보자라면 rank가 정해질때 reward랑 연결 되어야 하는게 아닐지? 그게 혹시 prize인건지?)
> 3. credit, debit, cancel이 하나로 표현했는데 각각의 flow가 약간씩 다를 것 같네요 - 이부분은 당장 수정을 할 필요는 없구요 기본 도메인을 그리면 화살표만 몇개 바꾸거나 하면 될것 으로 예상되어 추후 각각의 문서로 만들어 보는것도 좋을것 같네요.
> 
> 아마 제가 도메인을 자세히 몰라서 이해를 못한것일 수 있습니다. '보상결정', '순위결정' 같은 설명이 어딘가 추가된다면 좀더 이해가 편하지 않을까? 하네요.

1. 점선의 의미가 Point 배치를 의미한 것 입니다. Trigger 인 배치를 이용해서 저러한 History 데이터가 쌓인다를 의미하긴 했는데, 제가 봐도 잘 모르겠네요.. UML 도구를 써본적이없어서, 일종의 표현만 해두었습니다.
2. Reward가 Attendee 보다 먼저 생성되어있는게 맞습니다.
  - rank별 보상이 서로 상이한 브랜드와 사이트를 관리하는 별도의 테이블과도 연결되어있지만, 너무 딥하게 들어간 것 같아 제외했습니다.
  - reward id 당 rank 의 set이 한벌씩 뽑히고, 해당 rank 마다 prize 가 뽑혀서, A / B 브랜드에서 서로 같은 랭크라도 보상의 차이를 만들기 위해 저렇게 한것으로 알고있습니다.

~~ 한 배치라는 용어를 추가해서 목적성을 좀더 추가해두었습니다.

2023-12-05 12:11 UTC, titlet approved these changes
리뷰에 남기신 설명 잘 해주신 것 같습니다. 
수정된 부분도 확인해서 다음 단계로 진행하면 됩니다.
코멘트에 추가로 의견 드린 부분만 한번 확인 부탁 드립니다. 

수고하셨습니다.

2023-12-05 12:11 UTC, merged