add: 도메인 모델링
next-step/career-domain pull request #29
Opened 2024-05-03 16:24 UTC by hikjh

- 상세 도메인 다이어 그램, 추상화 도메인 다이어그램, 상세 도메인(우편발송) ERD, 상세 도메인(우편발송)

2024-05-04 05:11 UTC, titlet requested changes
오호 엄청 잘 그려주신것 같아요. 수고하셨습니다.
제가 도메인 지식이 없어서 그릴 수 있지만 몇가지만 이해안되는 부분 리뷰 남겼습니다. 
확인후 다시 PR요청 주십시오.

2024-05-04 05:11 UTC, titlet commented on Domain/domainModel-hikjh.md
> +    Post(우편)
우편은 방법으로 보여지는데요. 우편의 내용이 도메인이 아닐까? 하네요. 
저도 정확히는 모르겠지만 '조합승인', '조합정보', '게약'?? 무었일지 궁금하네요

2024-05-04 05:11 UTC, titlet commented on Domain/domainModel-hikjh.md
> +    Text(문자)
내용을 보니 '이용명세서'를 우편, 문자, 자료, 총회의 방법으로 하는 걸까요? 아닌거 같아서 이부분이 약간 이해하기 어렵긴 하네요

2024-05-04 05:11 UTC, titlet commented on Domain/domainModel-hikjh.md
> +    Text(문자)
ERD를 참조해보니 주문(혹은 계약)이라는 계념이 있는데 이건 도메인에는 표현이 안되어 보입니다.

2024-05-04 05:11 UTC, titlet commented on Domain/domainModel-hikjh.md
> +## 상세 도메인(우편발송)
상당히 잘 표현해 주셨어요.

2024-05-06 12:18 UTC, hikjh commented on Domain/domainModel-hikjh.md
> +    Text(문자)
> 내용을 보니 '이용명세서'를 우편, 문자, 자료, 총회의 방법으로 하는 걸까요? 아닌거 같아서 이부분이 약간 이해하기 어렵긴 하네요

실제 조합에서 사용하는 업무들중에 문자나 우편을 통해 소식들을 전달하는 업무가 있고, 등기나 토지 정보에 대한 자료들을 발급하는 업무가 있습니다. 또 시공사 선정과 같은 업무를 진행할때는 총회를 개설하여 조합원들의 투표에 따라 시공사를 선정합니다. 이러한 업무들이 오프라인으로 진행이 되어 있는데 저희 서비스를 사용하면서 온라인에서 사용이 가능하도록 서비스를 제공하고 이에 대한 비용처리(결제)를 서비스 요금으로 표현해봤습니다.

2024-05-06 12:18 UTC, hikjh commented on Domain/domainModel-hikjh.md
> +    Post(우편)
> 우편은 방법으로 보여지는데요. 우편의 내용이 도메인이 아닐까? 하네요. 저도 정확히는 모르겠지만 '조합승인', '조합정보', '게약'?? 무었일지 궁금하네요

우편의 내용은 조합 운영진이 조합 운영에 필요한 정보들을 조합원들에게 전달하는 용도로 사용됩니다.
예를 들어 시공사 선정을 할 경우 시공사들의 정보, 어떠한 안건에 대한 총회 정보 / 투표 결과

그래서 우편을 발송하는것 자체를 도메인으로 생각을 해봤습니다.

2024-05-06 12:18 UTC, hikjh commented on Domain/domainModel-hikjh.md
> +## 상세 도메인(우편발송)
> 상당히 잘 표현해 주셨어요.

감사합니다!

2024-05-07 14:26 UTC, titlet commented on Domain/domainModel-hikjh.md
> +    Post(우편)
아 잘 이야기 주신것 같네요. 
이야기 주신 내용으로 본다면 '시공사', '총회안건' '안건투표' 같은 것으로 보여지는데요. 혹시 이러한 내용들이 db table에 저장 된다면 이런 부분이 도메인이지 않을까요? 
즉, '안건투표'에 대한 내용을 email이나 우편으로 '고지' 하는 것이 데이터가 생성되는 기본 계념이 아닐지?

2024-05-07 14:30 UTC, titlet commented on Domain/domainModel-hikjh.md
> +    Text(문자)
> > 내용을 보니 '이용명세서'를 우편, 문자, 자료, 총회의 방법으로 하는 걸까요? 아닌거 같아서 이부분이 약간 이해하기 어렵긴 하네요
> 
> 실제 조합에서 사용하는 업무들중에 문자나 우편을 통해 소식들을 전달하는 업무가 있고, 등기나 토지 정보에 대한 자료들을 발급하는 업무가 있습니다. 또 시공사 선정과 같은 업무를 진행할때는 총회를 개설하여 조합원들의 투표에 따라 시공사를 선정합니다. 이러한 업무들이 오프라인으로 진행이 되어 있는데 저희 서비스를 사용하면서 온라인에서 사용이 가능하도록 서비스를 제공하고 이에 대한 비용처리(결제)를 서비스 요금으로 표현해봤습니다.

그렇다면 비용처리(결제)가 도메인이 맞지 않을까 하네요. 이 부분에서 본다면 

- 온라인으로 '투표' 하고 해당 '안건'에 '시공사선정' 같은 내용들이 있을것 같은데요. '투표'와 '안건'이 주요 도메인이 된다면 구현상에서도 확장성이 있어 보이긴 합니다. (두개를 합치면 '총회'가 되는 것일수도.)

2024-05-07 14:33 UTC, titlet requested changes
리뷰에 답변 주신 내용에서 추가로 리뷰 드렸습니다. 
도메인 모델을 완벽하게 그린 다기 보다는 이렇게 그릴 수 있는 방법을 익히는 거라 좀더 피드백을 드렸습니다.

2024-05-15 12:52 UTC, titlet approved these changes
핵심도메인과 서비도메인도 잘 구분해 주신것 같네요. 
해당 내용으로 한번 멘토링 진행시 이야기 나눠 보면 될것 같습니다. 
작성하시느라 수고하셨습니다.

2024-05-15 12:52 UTC, merged